export const LOAD_SESSIONS_SUCCESS = 'LOAD_SESSIONS_SUCCESS'
export const WORKOUT_STATUS = 'WORKOUT_STATUS'

export const GOT_DEFAULTS = 'GOT_DEFAULTS'
export const GOT_ERROR_LOADING_DEFAULTS = 'GOT_ERROR_GETTING_DEFAULTS'
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_VOID = 'AUTH_VOID'
export const AUTH_VOID_START = 'AUTH_VOID_START'
export const AUTH_ERROR = 'AUTH_ERROR'

export const EXERCISES_FETCHING_SUCCESS = 'EXERCISES_FETCHING_SUCCESS'
export const EXERCISES_FETCHING_ERROR = 'EXERCISES_FETCHING_ERROR'
export const EXERCISES_ORDER_CHANGE = 'EXERCISES_ORDER_CHANGE'
export const EXERCISES_MOVE_EXERCISE_TO_COMPLETED = 'EXERCISES_MOVE_EXERCISE_TO_COMPLETED'
export const EXERCISES_SAVED_RESULTS_SUCCESS = 'EXERCISES_SAVED_RESULTS_SUCCESS'
export const EXERCISES_SAVED_RESULTS_FAILED = 'EXERCISES_SAVED_RESULTS_FAILED'

export const SET_SUCCESSFULLY_COMPLETED = 'SET_SUCCESSFULLY_COMPLETED'
export const SET_FAILED = 'SET_FAILED'



