export const GET_LOCATION = 'GET_LOCATION'
export const GET_LOCATION_START = 'GET_LOCATION_START'
export const PING = 'PING'
export const LOAD_SESSIONS_SUCCESS = 'LOAD_SESSIONS_SUCCESS'
export const WORKOUT_STATUS = 'WORKOUT_STATUS'
export const EXERCISES_ORDER_CHANGE = 'EXERCISES_ORDER_CHANGE'

