export const GET_LOCATION = 'GET_LOCATION'
export const GET_LOCATION_START = 'GET_LOCATION_START'
export const PING = 'PING'
export const LOAD_SESSIONS_SUCCESS = 'LOAD_SESSIONS_SUCCESS'
export const WORKOUT_STATUS = 'WORKOUT_STATUS'

export const WORKOUT_STATUS_GET_READY = 'WORKOUT_STATUS_GET_READY'
export const WORKOUT_STATUS_TRAINING = 'WORKOUT_STATUS_TRAINING'
export const WORKOUT_STATUS_PREPARING = 'WORKOUT_STATUS_PREPARING'

export const PAUSE_STARTED = 'PAUSE_STARTED'
export const PAUSE_FINISHED = 'PAUSE_FINISHED'

export const GOT_DEFAULTS = 'GOT_DEFAULTS'
export const GOT_ERROR_LOADING_DEFAULTS = 'GOT_ERROR_GETTING_DEFAULTS'
export const START_AUTH = 'START_AUTH'
export const COMPLETE_AUTH = 'COMPLETE_AUTH'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'

export const EXERCISES_FETCHING_SUCCESS = ' EXERCISES_FETCHING_SUCCESS'
export const EXERCISES_FETCHING_ERROR = ' EXERCISES_FETCHING_ERROR'
export const EXERCISES_ORDER_CHANGE = 'EXERCISES_ORDER_CHANGE'

export const SET_SUCCESSFULLY_COMPLETED = 'SET_SUCCESSFULLY_COMPLETED'
export const SET_FAILED = 'SET_FAILED'



