export const types = {
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_VOID: 'AUTH_VOID',
    AUTH_VOID_START: 'FBASE:AUTH_VOID_START',
    AUTH_PROVIDER: 'FBASE:AUTH_PROVIDER',
    AUTH_GUEST: 'FBASE:AUTH_GUEST',
    AUTH_ERROR: 'AUTH_ERROR',
    EXERCISES_MOVE_EXERCISE_TO_COMPLETED: 'EXERCISES_MOVE_EXERCISE_TO_COMPLETED',
    EXERCISES_SAVED_RESULTS_SUCCESS : 'EXERCISES_SAVED_RESULTS_SUCCESS',
    EXERCISES_FETCHING_SUCCESS: 'EXERCISES_FETCHING_SUCCESS',
    EXERCISES_FETCHING_ERROR: 'EXERCISES_FETCHING_ERROR',

}
