export const types = {
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_VOID: 'AUTH_VOID',
    AUTH_VOID_START: 'AUTH_VOID_START',
    AUTH_ERROR: 'AUTH_ERROR',
    EXERCISES_FETCHING_SUCCESS: 'EXERCISES_FETCHING_SUCCESS',
    EXERCISES_FETCHING_ERROR: 'EXERCISES_FETCHING_ERROR'
}
